In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## เวลาจะใช้คำสั่งพวก np.random/numpy ต้อง import numpy as np ก่อน

In [ ]:
import numpy as np
np.random.rand()

## np.random.seed เอาไว้ล็อคผลเพื่อที่จะได้ผลออกมาที่เหมือนกัน

In [ ]:
np.random.seed(1)
np.random.randint(2,5)

## replace = False เลขที่ random ออกมาจะไม่ซํ้ากัน

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

## np.random.choice(5,3) เลือกค่ามา 3 ค่าจาก 5 ค่า

In [ ]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

## np.random.randint(10,size = (5,5)) คือ random ค่า 0-9 โดยขนาด 5*5

In [ ]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

In [ ]:
np_test= np.arange(25).reshape(5,5)
np_test

In [ ]:
data = np.random.randint(5,size=(5,5)) + 1
data

## np.argmax(data[1,:]) เลือกตำแหน่งที่มีค่าเยอะที่สุดของแถวที่ 1

In [ ]:
np.argmax(data[1,:])

# Ex.2

In [4]:
import numpy as np
np_matrix = np.random.rand(10,5)
last = np.round(np_matrix[:,4])
np_matrix[:,4] = last
np_matrix

array([[0.16509615, 0.57078184, 0.33661056, 0.51740636, 1.        ],
       [0.88147256, 0.70269868, 0.02145046, 0.87141276, 1.        ],
       [0.60168263, 0.90177327, 0.89710795, 0.10102495, 1.        ],
       [0.80831324, 0.48715057, 0.82543514, 0.59129429, 0.        ],
       [0.85972471, 0.92999666, 0.14039765, 0.84685517, 1.        ],
       [0.98079239, 0.27679471, 0.02835036, 0.4231737 , 1.        ],
       [0.85984458, 0.97846659, 0.47933268, 0.05065017, 0.        ],
       [0.10918555, 0.12920832, 0.1405915 , 0.67707626, 1.        ],
       [0.85561065, 0.93507646, 0.22471379, 0.97162353, 1.        ],
       [0.18477001, 0.11586623, 0.52783077, 0.58869736, 0.        ]])

# Ex.3

In [2]:
np_matrix = np.random.randint(11,size = (6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[ 0,  2,  8,  1,  9],
       [ 0,  4,  8,  3,  9],
       [ 6,  5, 10,  7,  8],
       [ 8,  2,  8,  0, 10],
       [ 5,  2,  0,  8,  1]])

# Ex.4

In [5]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[9, 1, 5, 8, 6],
       [7, 8, 0, 0, 6],
       [4, 2, 9, 9, 1],
       [0, 4, 5, 1, 8],
       [8, 6, 5, 3, 5],
       [7, 8, 2, 0, 1],
       [7, 7, 3, 3, 2],
       [1, 4, 5, 7, 0],
       [8, 6, 8, 1, 1],
       [9, 2, 8, 2, 0]])

In [6]:
label_vecter = np.random.randint(2,size = (10))
label_vecter

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1])

In [7]:
train_data = (label_vecter == 0)
np_matrix[train_data]

array([[9, 1, 5, 8, 6],
       [7, 8, 0, 0, 6],
       [7, 8, 2, 0, 1],
       [7, 7, 3, 3, 2]])

In [8]:
test_data = (label_vecter == 1)
np_matrix[test_data]

array([[4, 2, 9, 9, 1],
       [0, 4, 5, 1, 8],
       [8, 6, 5, 3, 5],
       [1, 4, 5, 7, 0],
       [8, 6, 8, 1, 1],
       [9, 2, 8, 2, 0]])

# Ex5

In [9]:
data = np.random.randint(6,size=(5,5))
data

array([[0, 0, 4, 3, 0],
       [5, 5, 5, 4, 0],
       [2, 0, 0, 3, 2],
       [3, 5, 4, 4, 1],
       [5, 1, 4, 2, 1]])

In [10]:
np.sort(data[0,:])[::-1]

array([4, 3, 0, 0, 0])

# Ex6

In [11]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np_test[np_test%3==0]

# Ex7

In [12]:
np_test[np.fill_diagonal(np_test,0)]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16, 17,  0, 19],
        [20, 21, 22, 23,  0]]])